### PR TITLE
Update Logo and Name

### PR DESCRIPTION
**Pull request by LanskoyGIB**
Please ensure your pull request (PR) adheres to the following guidelines:

- Please refer to our contributing documentation for any questions on submitting a pull request, link: [Contribution Guide](https://github.com/splunk-soar-connectors/.github/blob/main/.github/CONTRIBUTING.md)

#### Please check if your PR fulfills the following requirements:
- [ ] Testing of all the changes has been performed (for bug fixes / features)
- [ ] The readme.html has been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Use the following format for the PR description: `<App Name>: <PR Type> - <PR Description>`
- [ ] Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.
- [ ] Verify all checks are passing.
- [ ] Do NOT use the `next` branch of the forked repo. Create separate feature branch for raising the PR.
- [ ] Do NOT submit updates to dependencies unless it fixes an issue.
#### Please check the type of change your PR introduces:
- [ ] New App
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation
- [ ] Other (please describe): 

## Security Considerations (REQUIRED)
- [ ] If you are exposing any endpoints using a [REST handler](https://docs.splunk.com/Documentation/SOAR/current/DevelopApps/RESTHandlers), 
  please document them in the `readme.html`.
- [ ] If this is a new connector or you are adding new actions
    - [ ] Please document in the `readme.html` all methods (eg, OAuth) used to authenticate 
      with the service that the connector is integrating with.
    - [ ] If any actions are unable to run on SOAR Cloud, please document this in the `readme.html`.
- [ ] Are you introducing any new cryptography modules? If yes, please elaborate their purpose:
- [ ] Are you are accessing the file system? If yes, please verify that you are only accessing paths returned through 
the [Vault](https://docs.splunk.com/Documentation/SOARonprem/5.2.1/DevelopApps/AppDevAPIRef#Vault) API.
- [ ] Are you are marking code to be ignored by Semgrep with [`nosemgrep`](https://semgrep.dev/docs/ignoring-files-folders-code/#ignoring-code-through-nosemgrep)?
If yes, please provide justification in an additional comment next to the ignored code.

  

## Release Notes (REQUIRED)
- Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.

## What is the current behavior? (OPTIONAL)
- Describe the current behavior that you are modifying.

## What is the new behavior? (OPTIONAL)
- Describe the behavior or changes that are being added by this PR.

## Other information (OPTIONAL)
- Any other information that is important to this PR such as screenshots of how the component looks before and after the change.

## Pay close attention to (OPTIONAL)
- Any specific code change or test case points which must be addressed/reviewed at the time of GA release.

## Screenshots (if relevant)

---
Thanks for contributing!

### CODE REVIEW

**Comment by LanskoyGIB** [comment]
Hello,

I am new developer from Group-IB. What i should do if i want to rename our APP. Because as i understand from the report i can't just rename it into .json file
image

**Comment by spopat-crest** [comment]
Hello @dzaytsevGIB, Currently the min_phantom_version should be 5.4.0, could you please update it in the JSON file?

**Comment by LanskoyGIB** [comment]
Hello @spopat-crest , 
Yes i am already updated version, but my question is about how can i change name of the App because because name of our product was chaged and i want to change it.

**Comment by spopat-crest** [comment]
@dzaytsevGIB, Updating the name of the app in the JSON file will do, currently, you have updated the name to "Group IB Threat Intelligence", once the app will be released this will be reflected on the Splunkbase. Also I observed the logo file name is updated to "groupibthreatintelligenceandattribution.jpg", but I am not able to find any jpg file in the changes.

**Comment by LanskoyGIB** [comment]
@spopat-crest, It looks strange i'll create new PR with this files, a few questions before it.
1. Am i should use .svg file for logo or i can use .jpg?
2. Can i ignore erorr into _const file because it all static but many of collection which we have from the response have the same fields and we use this method to escape duplicate in code?

**Comment by spopat-crest** [comment]
@dzaytsevGIB, For the logo there should be .svg file and yes you can ignore the _const file error.

**Comment by LanskoyGIB** [comment]
@spopat-crest 
Thank you for your help

**Pull request closed without merging**
