### PR TITLE
PAPP-29398: Update Product name and other issue

### PR DESCRIPTION
**Pull request by LanskoyGIB**
Please ensure your pull request (PR) adheres to the following guidelines:

- Please refer to our contributing documentation for any questions on submitting a pull request, link: [Contribution Guide](https://github.com/splunk-soar-connectors/.github/blob/main/.github/CONTRIBUTING.md)

#### Please check if your PR fulfills the following requirements:
- [ ] Testing of all the changes has been performed (for bug fixes / features)
- [ ] The readme.html has been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Use the following format for the PR description: `<App Name>: <PR Type> - <PR Description>`
- [ ] Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.
- [ ] Verify all checks are passing.
- [ ] Do NOT use the `next` branch of the forked repo. Create separate feature branch for raising the PR.
- [ ] Do NOT submit updates to dependencies unless it fixes an issue.
#### Please check the type of change your PR introduces:
- [ ] New App
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation
- [ ] Other (please describe): 

## Security Considerations (REQUIRED)
- [ ] If you are exposing any endpoints using a [REST handler](https://docs.splunk.com/Documentation/SOAR/current/DevelopApps/RESTHandlers), 
  please document them in the `readme.html`.
- [ ] If this is a new connector or you are adding new actions
    - [ ] Please document in the `readme.html` all methods (eg, OAuth) used to authenticate 
      with the service that the connector is integrating with.
    - [ ] If any actions are unable to run on SOAR Cloud, please document this in the `readme.html`.
- [ ] Are you introducing any new cryptography modules? If yes, please elaborate their purpose:
- [ ] Are you are accessing the file system? If yes, please verify that you are only accessing paths returned through 
the [Vault](https://docs.splunk.com/Documentation/SOARonprem/5.2.1/DevelopApps/AppDevAPIRef#Vault) API.
- [ ] Are you are marking code to be ignored by Semgrep with [`nosemgrep`](https://semgrep.dev/docs/ignoring-files-folders-code/#ignoring-code-through-nosemgrep)?
If yes, please provide justification in an additional comment next to the ignored code.

  

## Release Notes (REQUIRED)
- Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.

## What is the current behavior? (OPTIONAL)
- Describe the current behavior that you are modifying.

## What is the new behavior? (OPTIONAL)
- Describe the behavior or changes that are being added by this PR.

## Other information (OPTIONAL)
- Any other information that is important to this PR such as screenshots of how the component looks before and after the change.

## Pay close attention to (OPTIONAL)
- Any specific code change or test case points which must be addressed/reviewed at the time of GA release.

## Screenshots (if relevant)

---
Thanks for contributing!

### CODE REVIEW

**Comment by spopat-crest** [comment]
@dzaytsevGIB The [min_phantom_version should be 5.4.0](https://github.com/splunk-soar-connectors/groupibthreatintelligenceandattribution/pull/2#issuecomment-1418715916), do you want to keep 5.3.0 only and you can update?

**Comment by LanskoyGIB** [comment]
@spopat-crest In a future we are planing global update of this integration.
I taked 5.3.0 from the last report 
image

**Comment by LanskoyGIB** [comment]
Hello @spopat-crest,

What else the main i should do to public this PR.

**Comment by spopat-crest** [comment]
@dzaytsevGIB, The PR looks good and no action is required from your side for now. We will review and proceed with the GA.

**Comment by LanskoyGIB** [comment]
Hello @spopat-crest,

Some another question how can we subscribe this App like "supported by developer", because for now it's marked is "unsupported by developer".
image

We have another app on Splunk base: https://splunkbase.splunk.com/app/6661 this app is marked as "supported by developer"

**Comment by spopat-crest** [comment]
@dzaytsevGIB To mark this app as "Developer Supported" please reach out to @nastorSplunk

**Comment by LanskoyGIB** [comment]
@spopat-crest Can you add him to this PR?
 
 If i should mail him can you please share with me his email because i didn't found it in his github account?

**Comment by spopat-crest** [comment]
@dzaytsevGIB Sure, He is the product manager of SOAR, here is his email Nicholas Astor: nastor@splunk.com

**Comment by LanskoyGIB** [comment]
Hello @spopat-crest,

Can you please, provide the PR status?

**Comment by spopat-crest** [comment]
@dzaytsevGIB, Do you want this app to be converted to developer supported or released as community supported only?

**Comment by LanskoyGIB** [comment]
@spopat-crest 
I think it will be good if we can release this app like Develop supported.

We already create request to make this app develop supported.
image

Field this form: https://docs.google.com/forms/d/e/1FAIpQLSecsmI3EmaesZrqWZbiCdhiiRkhNwy8eV_OLUODlWdQFeWEDg/viewform

**Comment by LanskoyGIB** [comment]
Hello @spopat-crest,

I have accessed the application admin panel, and have some questoins about it.
What is the right way to public new app throuht admin panel or PR on GitHub

**Comment by spopat-crest** [comment]
Hello @dzaytsevGIB, To public the app, current changes need to be merged in the main branch on GitHub. Currently, there are some static checks we are looking into, will inform you once it is done.

**Comment by LanskoyGIB** [comment]
Hello @spopat-crest,

Can you please, provide the PR status?

**Comment by spopat-crest** [comment]
@dzaytsevGIB We are in the progress of marking no_code_consts failure as expected failure, which should be done by today, meanwhile could you please resolve the remaining static failures(consistent_variable and light_and_dark_theme_logos) and linting failures

**Comment by spopat-crest** [comment]
Once all the checks are green you can merge the branch to next and proceed for release.

**Comment by LanskoyGIB** [comment]
Hello @spopat-crest,

Thank you for your response, i'll try to fix this points as soon as possible

**Comment by spopat-crest** [comment]
@dzaytsevGIB We have resolved all the failures from our side, the PR is ready to merge once you are done with the pipeline fixes. Do let us know if you require any help.

**Comment by LanskoyGIB** [comment]
Hello @spopat-crest,

I have fixed all the problems from the report, can we merge this PR now.

**Comment by spopat-crest** [comment]
@dzaytsevGIB There is lint failure as well, could you please look into it

**Comment by LanskoyGIB** [comment]
Hello @spopat-crest,

I have some issue with "linting error" i am little bit do not understand how to fix it. I look into integrations of others companes and linting.yml looks the same with us. Please, can you give some recomendation how can i fix it.

**Comment by aparekh-crest** [comment]
@dzaytsevGIB All checks are passing now, you can merge this pr and perform release processes as well.

**Comment by LanskoyGIB** [comment]
Hello @spopat-crest,

Can you mark this pr as reviewed or I need to wait for review from jdemelo?

**Comment by spopat-crest** [comment]
@dzaytsevGIB Yes we can review and approve

**Review by ishans-crest — APPROVED** [review]

**Comment by LanskoyGIB** [comment]
Hello @spopat-crest,

We already update logo on Git Hub but in Splunkstore ( https://splunkbase.splunk.com/app/5968 ) we still have old logo. What we should to change it?

**Comment by ishans-crest** [comment]
Hi @dzaytsevGIB 
It'll get automatically updated once the code is merged on main. We're doing some final checks and post that it'll get merged.

**Comment by spopat-crest** [comment]
@dzaytsevGIB The app is now released on Splunkbase and the logo is updated.

**Pull request merged**
