### PR TITLE
Ai 163

### PR DESCRIPTION
**Pull request by LanskoyGIB**
Please ensure your pull request (PR) adheres to the following guidelines:

- Please refer to our contributing documentation for any questions on submitting a pull request, link: [Contribution Guide](https://github.com/splunk-soar-connectors/.github/blob/main/.github/CONTRIBUTING.md)

#### Please check if your PR fulfills the following requirements:
- [ ] Testing of all the changes has been performed (for bug fixes / features)
- [ ] The readme.html has been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Use the following format for the PR description: `<App Name>: <PR Type> - <PR Description>`
- [ ] Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.
- [ ] Verify all checks are passing.
- [ ] Do NOT use the `next` branch of the forked repo. Create separate feature branch for raising the PR.
- [ ] Do NOT submit updates to dependencies unless it fixes an issue.
#### Please check the type of change your PR introduces:
- [ ] New App
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation
- [ ] Other (please describe): 

## Security Considerations (REQUIRED)
- [ ] If you are exposing any endpoints using a [REST handler](https://docs.splunk.com/Documentation/SOAR/current/DevelopApps/RESTHandlers), 
  please document them in the `readme.html`.
- [ ] If this is a new connector or you are adding new actions
    - [ ] Please document in the `readme.html` all methods (eg, OAuth) used to authenticate 
      with the service that the connector is integrating with.
    - [ ] If any actions are unable to run on SOAR Cloud, please document this in the `readme.html`.
- [ ] Are you introducing any new cryptography modules? If yes, please elaborate their purpose:
- [ ] Are you are accessing the file system? If yes, please verify that you are only accessing paths returned through 
the [Vault](https://docs.splunk.com/Documentation/SOARonprem/5.2.1/DevelopApps/AppDevAPIRef#Vault) API.
- [ ] Are you are marking code to be ignored by Semgrep with [`nosemgrep`](https://semgrep.dev/docs/ignoring-files-folders-code/#ignoring-code-through-nosemgrep)?
If yes, please provide justification in an additional comment next to the ignored code.

  

## Release Notes (REQUIRED)
- Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.

## What is the current behavior? (OPTIONAL)
- Describe the current behavior that you are modifying.

## What is the new behavior? (OPTIONAL)
- Describe the behavior or changes that are being added by this PR.

## Other information (OPTIONAL)
- Any other information that is important to this PR such as screenshots of how the component looks before and after the change.

## Pay close attention to (OPTIONAL)
- Any specific code change or test case points which must be addressed/reviewed at the time of GA release.

## Screenshots (if relevant)

---
Thanks for contributing!

### CODE REVIEW

**Comment by LanskoyGIB** [comment]
Hello, any update for this PR?

**Comment by LanskoyGIB** [comment]
Hello @spopat-crest,
As i remember you help us last time. Can you please review this PR?
Regards,
Daniil

**Comment by spopat-crest** [comment]
Hello @LanskoyGIB, As this is now developer supported connector, you might have merge rights and can merge this without the approval from engineering team.

Thanks,
Sweta

**Comment by LanskoyGIB** [comment]
Hello @spopat-crest,

But from my side it still looks like it was previosly
image

**Comment by spopat-crest** [comment]
Hello @nastorSplunk Could you please take look into this,
ref: https://github.com/splunk-soar-connectors/groupibthreatintelligenceandattribution/pull/3#issuecomment-1429525793

**Comment by LanskoyGIB** [comment]
I've changed my account username maybe it could be a problem

**Comment by LanskoyGIB** [comment]
Hello @spopat-crest,

While we waiting for respose from Nastor and resolving this issue, maybe you can approve this PR because all test are passed

**Comment by spopat-crest** [comment]
@LanskoyGIB I installed the build and verified the logos on both themes and it is not visible, could you explain why this change is made?
Screenshot 2023-03-21 at 3 13 03 PM

**Comment by LanskoyGIB** [comment]
Hello @spopat-crest,

In a market place it looks this 
image

**Comment by LanskoyGIB** [comment]
Hello @spopat-crest,

Any update?

**Comment by spopat-crest** [comment]
Hello @LanskoyGIB we should not update the logo file with the reason for it being not visible properly on Splunkbase. Doing so will break the app logo on Splunk SOAR.

cc: @nastorSplunk @ishans-crest

**Comment by LanskoyGIB** [comment]
Hello @spopat-crest,

But how i can make this logo visible because for now it's too bad quality https://splunkbase.splunk.com/app/5968
image

Into this PR i just swap logo for dark and light theme.

Can ypu suggest how i can make this logo more visible on market page

**Comment by spopat-crest** [comment]
@LanskoyGIB We have raised a bug for Splunkbase to make the logo visible properly, this is not an app issue so should not proceed with this PR.

**Comment by spopat-crest** [comment]
Also, you can look at the logo on classic Splunkbase https://classic.splunkbase.splunk.com/app/5968/, it is visible properly

**Comment by LanskoyGIB** [comment]
Hello @spopat-crest,

Thank you for help. Have a good day.

**Pull request closed without merging**
